function renderPlantCard(plant) {
  var strVar = ''
  strVar += '<div class="row plant-component">'
  strVar += '            <div class="col-md-6 component-img">'
  strVar += '              <img'
  strVar += '                src="' + plant.src + '"'
  strVar += '                alt="Smiley face"'
  strVar += '                width="100%" height="180px"'
  strVar += '              ></div>'
  strVar += '              <div class="col-md-6 component-info">'
  strVar += '                <div class="info-name">'
  strVar += '                  <strong>' + plant.name + '</strong>'
  strVar += '                  <span>' + plant.scientificName + '</span>'
  strVar += '                </div>'
  strVar += '                <div class="info-body">'
  strVar += '                  <p>Humidity (%): ' + plant.minH + ' ~ ' + plant.maxH + '</p>'
  strVar += '                  <p>Temperature (C): ' + plant.minT + ' ~ ' + plant.maxT + '</p>'
  strVar += '                  <p>Light (UV): ' + plant.minUv + ' ~ ' + plant.maxUv + '</p>'
  strVar += '                </div>'
  strVar += '              </div>'
  strVar += '          </div>'
  return strVar
}
